version: '3'
services:
  # MQTT Broker
  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped

  # MQTT Client in Docker
  mqtt-client:
    build:
      context: .
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
    volumes:
      - ./data:/app/data  # 确保数据持久化
    depends_on:
      - mqtt-broker
    command: ["node", "mqtt-client.js"]
    restart: unless-stopped

  # Node.js Backend Server
  web-server:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
    volumes:
      - ./data:/app/data
    depends_on:
      - mqtt-broker
      - mqtt-client
    command: ["node", "server.js"]
    restart: unless-stopped